
global:
  username: dk
  password: zhouyang
  # dev database
  dbUrl: jdbc:mysql://8.134.95.64:3306/notes240207_dev?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
  # prod database
#  dbUrl: jdbc:mysql://8.134.95.64:3306/notes230412?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true

