
global:
  username: dk
  password: consoleA1
  # dev database
  # dbUrl: jdbc:mysql://8.134.95.64:3306/notes240207_dev?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true

  # prod database 1
  # dbUrl: jdbc:mysql://8.134.95.64:3306/notes230412?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true

  # prod database 2
  dbUrl: jdbc:mysql://rm-wz99kfxt13jnuimburo.mysql.rds.aliyuncs.com:3306/notes230412?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true

