spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zhouyang
    url: jdbc:mysql://localhost:3306/notesWx230618?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
#  elasticsearch:
#    host: localhost
#    port: 9200
#    username: elastic
#    password: VMZmuH6EZNYr1ZvXpttT

