spring:
  application:
    name: GatewayService

server:
  port: 80

logging:
  logback:
    rollingpolicy:
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.log"
  file:
    name: ./logs/NoteServer.log
