spring:
  application:
    name: GatewayService
  profiles:
    active: local

server:
  port: 80

logging:
  logback:
    rollingpolicy:
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.log"
  file:
    name: ./logs/Geteway-%d{yyyy-MM-dd}.log
    path: ./logs
