server:
  port: 9090
#  port: 443    #HTTPS协议默认端口号为443，需要使用其他端口时，您可以在此处自定义。
#  ssl:
#    key-store-password: 8mcnnd7v    #填写jks-password.txt文件内的密码。
#    key-store-type: JKS #JKS格式证书密钥库类型。PFX格式的证书密钥库类型为PKCS12。
#    key-store: classpath:aboutdk.cn.jks   #您需要使用实际的证书名称替换domain_name.jks。

spring:
  application:
    name: GatewayService
#  cloud:
#    nacos:
#      discovery:
#        server-addr: http://113.44.7.213:8848/ # 华为云
#        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: NoteApplication
#          uri: http://114.132.189.139:8081 # 腾讯云
          uri: http://localhost:8081
          predicates:
            - Path=/api/note/**

logging:
  logback:
    rollingpolicy:
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.log"
  file:
    name: ./logs/Gateway/Gateway-%d{yyyy-MM-dd}.log
    path: ./logs
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route: DEBUG
    org.springframework.cloud.gateway.route.builder: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: DEBUG

