spring:
  application:
    name: SnowflakeidApplication
  main:
    web-application-type: servlet
  jackson:
    #日期格式化
    #date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: zhouyang
#    url: jdbc:mysql://localhost:3306/notesWx230618?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: dk
    password: zhouyang
    url: jdbc:mysql://8.134.95.64:3306/notes240207_dev?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true

server:
  port: 8082


logging:
  logback:
    rollingpolicy:
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.log"
  file:
    name: ./logs/NoteServer.log
