spring:
  application:
    name: SnowflakeidApplication
  main:
    web-application-type: servlet
  jackson:
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${global.username}
    password: ${global.password}
    url: ${global.remoteDBUrl}

server:
  port: 8082
#  servlet:
#    context-path: /api

logging:
  logback:
    rollingpolicy:
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.log"
  file:
    name: ./logs/NoteServer.log
