spring:
  application:
    name: SnowflakeidApplication
  main:
    web-application-type: servlet
  jackson:
    time-zone: GMT+8
  profiles:
    active: local

server:
  port: 8082
#  servlet:
#    context-path: /api

logging:
  logback:
    rollingpolicy:
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.log"
  file:
    name: ./logs/NoteServer.log
