spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zhouyang
    url: jdbc:mysql://host.docker.internal:3306/notes230412?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.0.2:8761/eureka/
  instance:
    prefer-ip-address: true
