server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
#  logback:
#    rollingpolicy:
#      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.log"
  file:
    name: ./logs/discover-service/discover-service-%d{yyyy-MM-dd}.log
    path: ./logs/discover-service