spring:
  application:
    name: NoteApplication
  main:
    web-application-type: servlet
  jackson:
    #日期格式化
    #date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dk
    password: 159357123Ab
    url: ${global.dbUrl}

server:
  port: 8081
  servlet:
    context-path: /api/note

logging:
  file:
    name: ./logs/Note/Note-%d{yyyy-MM-dd}.log
    path: ./logs

eureka:
  instance:
    ip-address: localhost
    hostname: localhost
    home-page-url: http://localhost:8081/
    health-check-url: http://localhost:8081/api/note/actuator/health
    status-page-url: http://localhost:8081/api/note/actuator/info

  #    ip-address: 119.23.74.175
  #    hostname: 119.23.74.175
  #    home-page-url: http://119.23.74.175:8081/
  #    health-check-url: http://119.23.74.175:8081/api/note/actuator/health
  #    status-page-url: http://119.23.74.175:8081/api/note/actuator/info
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://114.132.189.139:8761/eureka/

