spring:
  application:
    name: NoteApplication
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    web-application-type: servlet
  jackson:
    #日期格式化
    #date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dk
    password: 159357123Ab
    url: ${global.dbUrl}

server:
  port: 8081
  servlet:
    context-path: /api/note

logging:
  file:
    name: ./logs/Note/Note-%d{yyyy-MM-dd}.log
    path: ./logs


